import webbrowser
from time import sleep

from generate_ideas import generate_ideas
from generate_image import generate_image

pattern_ideas = generate_ideas("3 top pattern ideas that can be generated by ai")
for pi in pattern_ideas:
    print(f"\n{pi}")
    pattern_idea_samples = generate_ideas(f"only list 3 {pi} that's in demand")
    for pis in pattern_idea_samples:
        image_url = generate_image(f"fabric pattern {pis}")
        print(f"  - {pis}: {image_url}")
        webbrowser.open(image_url)
        sleep(60)
